services:  
  samba:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: samba
    hostname: ${SAMBADC_HOSTNAME:-dc1.cyberbean.lan}
    environment:
      DOMAIN_ACTION: provision
      INTERFACES: ${SAMBADC_INTERFACES:-lo docker0 wlan0}
      REALM: ${SAMBA_REALM:-cyberbean.lan}
      TZ: ${TZ:-UTC}
      WORKGROUP: ${SAMBA_WORKGROUP:-cyberbean}
      ALLOW_LDAP_INSECURE: true
      LOG_LEVEL: 5
    restart: always
    cap_add:
      - NET_ADMIN
      - CAP_SYS_ADMIN
    network_mode: host
    dns:
      - 192.168.50.138
      - 172.17.0.1
    volumes:
      - ./vols/samba:/var/lib/samba
      - ./vols/samba-conf:/etc/samba
      - ./conf/supervisor:/etc/supervisor
    secrets:
      - samba-admin-password

secrets:
  samba-admin-password:
    file: ./conf/adm-passwd.txt

networks:
  samba:
